---
- hosts: localhost
  tasks:
    - name: Launch a new container
      docker_container:
        name: my-container
        image: kabir/ubuntu-ssh:v1
        state: started
        detach: yes
        interactive: yes
        tty: yes
        ports:
          - "80:80"

    - name: Container details
      docker_container_info:
        name: "my-container"
      register: containerinfo

    - debug:
        var: containerinfo.container.NetworkSettings.IPAddress

    - name: Create inventory file
      template:
        src: /etc/ansible/hosts
        dest: /tmp/inventory/inventory_template

- hosts: all
  become: true  # Run tasks with elevated privileges (sudo)

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      systemd:
        name: apache2
        state: started

    - name: Copy index.html to web servers
      copy:
        src: /home/ubuntu/index.html
        dest: /var/www/html/index.html

